=== restincode/restincode/schema/person.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://restincode.com/schema/person.schema.json",
  "title": "RestInCode memorial entry",
  "description": "Shape of a people/<name>.json file. See people/_template.json for a starting point.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "firstname",
    "lastname",
    "handle",
    "birth",
    "death",
    "obituary",
    "issue",
    "affiliations",
    "mainimage",
    "maintext",
    "socialmedialinks",
    "references",
    "contributions",
    "gallery"
  ],
  "properties": {
    "firstname": { "type": "string" },
    "lastname": { "type": "string" },
    "handle": { "type": "string" },
    "birth": { "type": "string" },
    "death": { "type": "string" },
    "obituary": { "type": "string" },
    "issue": {
      "type": "string",
      "pattern": "^[0-9]*$",
      "description": "GitHub issue number as a string, or empty"
    },
    "affiliations": { "type": "string" },
    "mainimage": { "type": "string", "minLength": 1 },
    "maintext": {
      "type": "string",
      "description": "Raw HTML. This is the only field rendered as HTML."
    },
    "socialmedialinks": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["sitename", "siteurl"],
        "properties": {
          "sitename": { "type": "string", "minLength": 1 },
          "siteurl": { "type": "string", "minLength": 1 }
        }
      }
    },
    "references": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["title", "url"],
        "properties": {
          "title": { "type": "string", "minLength": 1 },
          "url": { "type": "string", "minLength": 1 }
        }
      }
    },
    "contributions": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["title", "url", "description"],
        "properties": {
          "title": { "type": "string", "minLength": 1 },
          "url": { "type": "string" },
          "description": { "type": "string" }
        }
      }
    },
    "gallery": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["url", "caption"],
        "properties": {
          "url": { "type": "string", "minLength": 1 },
          "title": { "type": "string" },
          "caption": { "type": "string" }
        }
      }
    }
  }
}

=== restincode/restincode/people/karenKrystalia.json
{
  "firstname": "Karen",
  "lastname": "",
  "handle": "Krystalia",
  "birth": "",
  "death": "October 29 1999",
  "obituary": "http://krystalia.org/",
  "issue": "132",
  "affiliations": "",
  "mainimage": "/images/karen_krystalia.jpg",
  "maintext": "<p>People Die. People Die Every day. People who are as loving, kind hearted, caring, and as radiant as Krystalia never die. Her memory will live on in our hearts forever.</p><p> Krystalia passed away at 12:30PM on October 29th, 1999. She was battling ovarian cancer that was diagnosed about 10 months prior. In her last few months it spread to her major organs, sending her into a coma early Friday morning, and then her heart stopped and she passed away that afternoon. Her family was at her side.</p><p> Daily Krystalia is bringing out the best in people. I get E-mails every day from random people telling me how sorry they are, and how they feel our loss. Everyones words are very kind, we appreciate it very much. Thank you.</p>",
  "socialmedialinks": [],
  "references": [],
  "contributions": [],
  "gallery": []
}

=== restincode/restincode/people/tfreak.json
{
  "firstname": "",
  "lastname": "",
  "handle": "TFreak",
  "birth": "",
  "death": "2010",
  "obituary": "",
  "issue": "297",
  "affiliations": "",
  "mainimage": "/images/face-silhouette-clipart.png",
  "maintext": "<p>TFreak was a hacker known for creating the smurf attack, a distributed denial-of-service attack that exploits the Internet Control Message Protocol (ICMP). The smurf attack was one of the most well-known and widely discussed network attacks of the late 1990s.</p>",
  "socialmedialinks": [
    {
      "sitename": "Hackepedia",
      "siteurl": "https://hackepedia.org/?title=Tfreak"
    },
    {
      "sitename": "Wikipedia - Smurf Attack",
      "siteurl": "https://en.wikipedia.org/wiki/Smurf_attack"
    },
    {
      "sitename": "Bugtraq Post",
      "siteurl": "https://seclists.org/bugtraq/1997/Oct/66"
    }
  ],
  "references": [],
  "contributions": [],
  "gallery": []
}

=== restincode/restincode/people/adrianlamo.json
{
  "firstname": "Adrian",
  "lastname": "Lamo",
  "handle": "",
  "birth": "1981",
  "death": "2018",
  "obituary": "",
  "issue": "209",
  "affiliations": "2600",
  "mainimage": "/images/face-silhouette-clipart.png",
  "maintext": "<p>Adrian Lamo was an American threat analyst and hacker. Known as the \"homeless hacker\" for his nomadic lifestyle, Lamo gained attention for breaking into several high-profile computer networks including those of The New York Times, Yahoo!, and Microsoft. He was later known for reporting Chelsea Manning to the U.S. Army in 2010 after Manning confided in him about leaking classified documents to WikiLeaks. Lamo was found dead in a Wichita, Kansas apartment in 2018 at the age of 37.</p>",
  "socialmedialinks": [
    {
      "sitename": "Facebook",
      "siteurl": "https://www.facebook.com/LordlOfTheRings"
    },
    {
      "sitename": "Other",
      "siteurl": "https://www.npr.org/2019/09/19/760317486/the-mysterious-death-of-the-hacker-who-turned-in-chelsea-manning"
    }
  ],
  "references": [],
  "contributions": [],
  "gallery": []
}

=== restincode/restincode/people/chrisnightstalker.json
{
  "firstname": "Chris",
  "lastname": "",
  "handle": "The Nightstalker",
  "birth": "",
  "death": "",
  "obituary": "https://web.archive.org/web/20181021094502/http://w3.cultdeadcow.com/cms/nightstalker.html",
  "issue": "201",
  "affiliations": "Cult of the Dead Cow",
  "mainimage": "/images/face-silhouette-clipart.png",
  "maintext": "<p>Chris, known as The Nightstalker, was a member of Cult of the Dead Cow (cDc), one of the oldest and most influential hacking groups in the United States.</p>",
  "socialmedialinks": [],
  "references": [],
  "contributions": [],
  "gallery": []
}

=== restincode/restincode/people/donaldskelton.json
{
  "firstname": "Donald",
  "lastname": "Skelton",
  "handle": "",
  "birth": "1989",
  "death": "2023",
  "obituary": "",
  "issue": "191",
  "affiliations": "303",
  "mainimage": "/images/DonaldSkelton.webp",
  "maintext": "<p>Donald Duane Skelton was a member of the 303 hacking group. He passed away on January 18, 2023, after a prolonged battle with illness. He is survived by his wife and two sons.</p>",
  "socialmedialinks": [
    {
      "sitename": "GoFundMe",
      "siteurl": "https://www.gofundme.com/f/donald-dwayne-skelton"
    }
  ],
  "references": [],
  "contributions": [],
  "gallery": []
}

=== restincode/restincode/people/bruceesquibel.json
{
  "firstname": "Bruce",
  "lastname": "Esquibel",
  "handle": "Dr. Ripco",
  "birth": "10 Mar 1959",
  "death": "24 Nov 2022",
  "obituary": "",
  "issue": "193",
  "affiliations": "",
  "mainimage": "/images/bruce_esquibel1.jpg",
  "maintext": "<p>Bruce Esquibel, also known as \"Dr. Ripco,\" ran a long-standing Chicago-based BBS known as Ripco BBS. Recognized as one of Chicago's most notable BBSes, it was well-known for being a freewheeling, wide-ranging board. On May 8, 1990, Agents of the United States Secret Service, along with police and telephone company security personnel, executed thirty-two search warrants across the United States in Operation Sun Devil. Ripco BBS was swept up during the raids. The actions of the Secret Service in confiscating the board's equipment constituted an infringement on freedom, underlining the critical role BBSes play as platforms for exchanging thoughts and disseminating information. Ripco became reborn as an ISP in the 1990s.</p>",
  "socialmedialinks": [],
  "references": [
    {
      "title": "textfiles memorial tweet",
      "url": "https://twitter.com/textfiles/status/1625878219114127362"
    },
    {
      "title": "DethVeggie memorial tweet",
      "url": "https://twitter.com/DethVeggie/status/1626016692613812224"
    }
  ],
  "contributions": [
    {
      "title": "Dr. Ripco's Last Stand",
      "url": "https://archive.org/details/ripcoslaststand",
      "description": "A collection of gathered media of interest to Bruce \"Dr. Ripco\" Esquibel. Archived by Jason Scott."
    },
    {
      "title": "Closing the Net",
      "url": "http://www.costik.com/hackers.html",
      "description": "January 1991 issue of Reason magazine. Detailing events that took place during Operation Sun Devil."
    },
    {
      "title": "BBS Documentary Video",
      "url": "https://archive.org/details/bbs-20040123-ripco/Doctor+Ripco+-+Tape+1.avi",
      "description": "Full BBS Documentary Interview: Dr. Ripco"
    },
    {
      "title": "January 23, 2004 BBS Documentary",
      "url": "http://www.bbsdocumentary.com/photos/129ripco/",
      "description": "Support files and related documents for BBS Documentary"
    },
    {
      "title": "Chicago Site Gets the Shaft",
      "url": "https://www.wired.com/1999/09/chicago-site-gets-the-shaft/",
      "description": "Ripco Communications redirected two domains belonging to La Raza, a weekly paper with a circulation 150,000, to dildo.com for not paying its bills."
    }
  ],
  "gallery": [
    {
      "url": "/images/bruce_esquibel2.jpg",
      "title": "Dr. Ripco and Jason Scott with the original Apple II Ripco BBS ran on.",
      "caption": "Dr. Ripco and Jason Scott with the original Apple II Ripco BBS ran on."
    }
  ]
}

=== restincode/restincode/people/nickjeremicah.json
{
  "firstname": "Nick",
  "lastname": "Jeremicah",
  "handle": "Dr. Nick2000",
  "birth": "1977",
  "death": "2006",
  "obituary": "",
  "issue": "35",
  "affiliations": "Goon",
  "mainimage": "https://www.defcon.org/images/links/whois/drnick.jpg",
  "maintext": "<p>Dr Nick aka Nick Jeremicah lost the battle against cancer in the fall of 2006.<br /><br />He is survived by his parents, siblings, wife and two children.<br /><br />Dr Nick2000 was 30 years old.</p>",
  "socialmedialinks": [],
  "references": [],
  "contributions": [],
  "gallery": []
}

=== restincode/restincode/people/timskorick.json
{
  "firstname": "Tim",
  "lastname": "Skorick",
  "handle": "Timmah",
  "birth": "",
  "death": "2026",
  "obituary": "",
  "issue": "304",
  "affiliations": "303",
  "mainimage": "/images/face-silhouette-clipart.png",
  "maintext": "<p>Tim Skorick, known as Timmah, was a member of the 303 hacking group and the information security community.</p>",
  "socialmedialinks": [
    {
      "sitename": "GoFundMe",
      "siteurl": "https://www.gofundme.com/f/support-for-the-skorick-family"
    }
  ],
  "references": [],
  "contributions": [],
  "gallery": []
}
