=== restincode/restincode/schema/person.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://restincode.com/schema/person.schema.json",
  "title": "RestInCode memorial entry",
  "description": "Shape of a people/<name>.json file. See people/_template.json for a starting point.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "firstname",
    "lastname",
    "handle",
    "birth",
    "death",
    "obituary",
    "issue",
    "affiliations",
    "mainimage",
    "maintext",
    "socialmedialinks",
    "references",
    "contributions",
    "gallery"
  ],
  "properties": {
    "firstname": { "type": "string" },
    "lastname": { "type": "string" },
    "handle": { "type": "string" },
    "birth": { "type": "string" },
    "death": { "type": "string" },
    "obituary": { "type": "string" },
    "issue": {
      "type": "string",
      "pattern": "^[0-9]*$",
      "description": "GitHub issue number as a string, or empty"
    },
    "affiliations": { "type": "string" },
    "mainimage": { "type": "string", "minLength": 1 },
    "maintext": {
      "type": "string",
      "description": "Raw HTML. This is the only field rendered as HTML."
    },
    "socialmedialinks": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["sitename", "siteurl"],
        "properties": {
          "sitename": { "type": "string", "minLength": 1 },
          "siteurl": { "type": "string", "minLength": 1 }
        }
      }
    },
    "references": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["title", "url"],
        "properties": {
          "title": { "type": "string", "minLength": 1 },
          "url": { "type": "string", "minLength": 1 }
        }
      }
    },
    "contributions": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["title", "url", "description"],
        "properties": {
          "title": { "type": "string", "minLength": 1 },
          "url": { "type": "string" },
          "description": { "type": "string" }
        }
      }
    },
    "gallery": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["url", "caption"],
        "properties": {
          "url": { "type": "string", "minLength": 1 },
          "title": { "type": "string" },
          "caption": { "type": "string" }
        }
      }
    }
  }
}

=== restincode/restincode/people/reverendrat.json
{
  "firstname": "",
  "lastname": "",
  "handle": "Reverend Rat",
  "birth": "",
  "death": "",
  "obituary": "",
  "issue": "184",
  "affiliations": "",
  "mainimage": "/images/face-silhouette-clipart.png",
  "maintext": "<p>Reverend Rat was a member of the hacker and information security community.</p>",
  "socialmedialinks": [
    {
      "sitename": "Twitter Memorial",
      "siteurl": "https://twitter.com/marcwrogers/status/1438186471907737600"
    }
  ],
  "references": [],
  "contributions": [],
  "gallery": []
}

=== restincode/restincode/people/bretmattingly.json
{
  "firstname": "Bret",
  "lastname": "Mattingly",
  "handle": "Delta",
  "birth": "1992",
  "death": "2019",
  "obituary": "https://www.legacy.com/obituaries/indystar/obituary.aspx?n=bret-oliver-mattingly&pid=191620602&fhid=14455",
  "issue": "29",
  "affiliations": "",
  "mainimage": "/images/Bret_Mattingly.jpg",
  "maintext": "",
  "socialmedialinks": [
    {
      "sitename": "Twitter",
      "siteurl": "https://www.twitter.com/adeptisdelta"
    },
    {
      "sitename": "Instagram",
      "siteurl": "https://www.instagram.com/justtcallmedelta/"
    },
    {
      "sitename": "LinkedIn",
      "siteurl": "https://www.linkedin.com/in/bretmattinglyii"
    }
  ],
  "references": [],
  "contributions": [],
  "gallery": []
}

=== restincode/restincode/people/karlkoch.json
{
  "firstname": "Karl",
  "lastname": "Koch",
  "handle": "",
  "birth": "1965",
  "death": "1989",
  "obituary": "",
  "issue": "23",
  "affiliations": "",
  "mainimage": "/images/face-silhouette-clipart.png",
  "maintext": "",
  "socialmedialinks": [
    {
      "sitename": "Wikipedia",
      "siteurl": "https://en.wikipedia.org/wiki/Karl_Koch_(hacker)"
    }
  ],
  "references": [],
  "contributions": [],
  "gallery": []
}

=== restincode/restincode/people/obsèquesdepaolo.json
{
  "firstname": "Obsèques",
  "lastname": "de Paolo",
  "handle": "",
  "birth": "",
  "death": "",
  "obituary": "",
  "issue": "20",
  "affiliations": "",
  "mainimage": "/images/face-silhouette-clipart.png",
  "maintext": "",
  "socialmedialinks": [],
  "references": [],
  "contributions": [],
  "gallery": []
}

=== restincode/restincode/people/christopherfudge.json
{
  "firstname": "Christopher",
  "lastname": "Fudge",
  "handle": "",
  "birth": "July 8, 1957",
  "death": "November 19, 2019",
  "obituary": "https://everdays.com/funeral-homes/usa/co/centennial/horan--mcconaty---south-metrocentennial/christopher-reid-fudge",
  "issue": "127",
  "affiliations": "ISSA",
  "mainimage": "/images/christopherfudge.jpg",
  "maintext": "<p>Reid, Fudge passed away peacefully at age 62 on November 19th, 2019 in Highlands Ranch Colorado. He will forever be remembered by all those who met him as a kind-hearted soul that warmed any room he walked into. His journey in this life began in Jacksonville, Florida on July 8th, 1957. Born to two loving parents Linda and Donald Fudge.\n Reid is survived by his loving wife and life-long partner of 44 years, Linda Fudge; his brother John Fudge; sister Lucia Hazen; mother Linda Smith; daughter Jade Hirvela; son Dylan Fudge; daughter-in-law Vianey Fudge; son-in-law Bo Hirvela; grand-son Tychus Fudge; grand-daughter Kaylee Cortez; niece Savannah Hazen; and nephew Hunter Hazen.</p><p> It was while attending college at the University of Florida he met the woman that changed his life forever, Linda Swanson soon to be Fudge. Their relationship quickly blossomed into a beautiful marriage. Following graduation, they both moved to Colorado where Reid’s career fell into the world of information technology. He quickly advanced within the IT field pioneering many novel methods. Reid’s fast career progress can partly be attributed to his hard work ethic and keen intellect although these traits applied to anything Reid put his mind to which expanded far beyond his career.</p><p> Reid was a person of faith. He had a passion for politics, horticulture, guitars, guns, golfing, culinary delights, and travel. One passion he held high above the rest was the love for his family. His love for his family and friends was unconditional and obvious in the time he dedicated to them. His wisdom, kindness, patience, and love will always be admired and sorely missed.</p><p> Reid Fudge was dearly loved by so many and will be missed beyond measure.A ceremony will be held Saturday, 11.23.2019 at 3 PM at St. Timothy’s Episcopal Church; 1401 East Dry Creek Rd., Littleton, CO, 80122. Donations may be sent to the St. Jude Children’s Hospital in Reid’s honor.</p>",
  "socialmedialinks": [
    {
      "sitename": "LinkedIn",
      "siteurl": "https://www.linkedin.com/in/reid-fudge-3bb9151/"
    }
  ],
  "references": [],
  "contributions": [
    {
      "title": "CISO at Tri-State Generation",
      "url": "",
      "description": ""
    }
  ],
  "gallery": []
}

=== restincode/restincode/people/borisfloricic.json
{
  "firstname": "Boris",
  "lastname": "Floricic",
  "handle": "Tron",
  "birth": "1972",
  "death": "1998",
  "obituary": "",
  "issue": "24",
  "affiliations": "",
  "mainimage": "/images/face-silhouette-clipart.png",
  "maintext": "<p>Boris Floricic, better known by his pseudonym Tron, was a German hacker and phreaker whose death in unclear circumstances has led to various conspiracy theories. He is also known for his Diplom thesis presenting one of the first public implementations of a telephone with built-in voice encryption, the 'Cryptophon'.</p><p>Floricic's pseudonym was a reference to the eponymous character in the 1982 Disney film Tron. Floricic was interested in defeating computer security mechanisms; amongst other hacks, he broke the security of the German phonecard and produced working clones. He was subsequently sentenced to 15 months in jail for the physical theft of a public phone (for reverse engineering purposes) but the sentence was suspended to probation.</p>",
  "socialmedialinks": [
    {
      "sitename": "Twitter",
      "siteurl": "https://twitter.com/assante_michael"
    },
    {
      "sitename": "Wikipedia",
      "siteurl": "https://en.wikipedia.org/wiki/Tron_(hacker)"
    }
  ],
  "references": [],
  "contributions": [],
  "gallery": []
}

=== restincode/restincode/people/kelvinwhite.json
{
  "firstname": "Kelvin",
  "lastname": "White",
  "handle": "L3thal",
  "birth": "Oct 24th 1977",
  "death": "Apr 4th 2017",
  "obituary": "",
  "issue": "128",
  "affiliations": "SmashTheStack",
  "mainimage": "/images/kelvin_white_l3thal.jpeg",
  "maintext": "<p>Kelvin White (a.k.a. l3thal) graced the world with his presence for just 39 years, but he lived every moment of it to the max. If you were lucky enough to meet him, you either instantly connected or not, with no awkward stage in between.</p>",
  "socialmedialinks": [
    {
      "sitename": "Twitter",
      "siteurl": "https://twitter.com/l3thal_sts"
    },
    {
      "sitename": "Github",
      "siteurl": "https://github.com/l3thal"
    },
    {
      "sitename": "Facebook",
      "siteurl": "https://www.facebook.com/outlawscumbag"
    },
    {
      "sitename": "Facebook Memorial",
      "siteurl": "https://www.facebook.com/kelvinwhitelethal/"
    }
  ],
  "references": [],
  "contributions": [
    {
      "title": "SmashTheStack",
      "url": "https://www.smashthestack.org/",
      "description": "L3thal was a co-creator and admin for the SmashTheStack WarGames website and services. This included the maintenance of infrastructure, development of new games and their individual challenges."
    },
    {
      "title": "Buffer Overflow Tutorial",
      "url": "https://smashthestack.org/l3thal/bof.txt",
      "description": "This was a commonly referenced overflow tutorial that l3thal wrote for newbies on the SmashTheStack IRC network."
    }
  ],
  "gallery": [
    {
      "url": "/images/kelvin_white_l3thal_classic_1992_age-15.jpeg",
      "title": "Classic Kelvin. *swoon* (circa 1992, age 15)",
      "caption": "Photo of l3thal at age 15 (1992)"
    },
    {
      "url": "/images/kelvin_white_l3thal_keyboard.jpeg",
      "title": "l3thal avatar",
      "caption": "Photo of l3thal wearing a mask and holding a keyboard like a rifle"
    },
    {
      "url": "/images/kelvin_white_l3thal_last-known-photo.jpeg",
      "title": "Last known photo: 4/15 12am. Crazy as always.",
      "caption": "The last known photo of l3thal"
    },
    {
      "url": "/images/kelvin_white_l3thal_memorial_banner.png",
      "title": "Memorial banner (l3thal edit)",
      "caption": "A memorial banner of multiple photos in honor of l3thal"
    },
    {
      "url": "/images/kelvin_white_l3thal_punk.jpeg",
      "title": "That perfect punk snarl.",
      "caption": "Photo of l3thal dressed in his usual punk attire"
    },
    {
      "url": "/images/kelvin_white_l3thal_STS-at-DEFCON.jpeg",
      "title": "Photo of l3thal (front/center hugging mauvehed) and other anonymous SmashTheStack members at DEF CON",
      "caption": "Photo of l3thal (front/center hugging mauvehed) and other anonymous SmashTheStack members at DEF CON"
    },
    {
      "url": "/images/kelvin_white_star-struck.jpeg",
      "title": "Love in our star-struck eyes, immortalized. (either that or we mighta been smacked out that night)",
      "caption": "Photo of Kelvin and wife Kelli"
    }
  ]
}

=== restincode/restincode/people/ianmurdock.json
{
  "firstname": "Ian",
  "lastname": "Murdock",
  "handle": "",
  "birth": "1973",
  "death": "2015",
  "obituary": "",
  "issue": "25",
  "affiliations": "",
  "mainimage": "/images/Ian_Murdock.jpg",
  "maintext": "<p>While a college student, Murdock founded the Debian project in August 1993, and wrote the Debian Manifesto in January 1994. Murdock conceived Debian as a Linux distribution that embraced open design, contributions, and support from the free software community. He named Debian after his then-girlfriend (later wife) Debra Lynn, and himself (Deb and Ian). They later married, had three children, and divorced in January 2008. In January 2006, Murdock was appointed Chief Technology Officer of the Free Standards Group and elected chair of the Linux Standard Base workgroup. He continued as CTO of the Linux Foundation when the group was formed from the merger of the Free Standards Group and Open Source Development Labs.</p>",
  "socialmedialinks": [],
  "references": [],
  "contributions": [
    {
      "title": "Debian",
      "url": "https://en.wikipedia.org/wiki/Debian",
      "description": "Debian (/ˈdɛbiən/) is a Unix-like operating system composed of free and open-source software. Ian Murdock founded the Debian Project on August 16, 1993."
    }
  ],
  "gallery": []
}
